export const slugifyText = (text: string): string => text.normalize('NFD')
  .split('')
  .filter(character => character.charCodeAt(0) <= 127)
  .join('')
  .toLowerCase()
  .split(' ')
  .join('-')
  .split('_')
  .join('-')
